catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'book/', views.BookListView.as_view(), name='books'),
    path(r'book/<str:pk>/', views.BookDetailView.as_view(), name='detail'),
    path(r'mybooks/', views.LoanedBookByUser.as_view(), name='borrowed'),
    path('book/<uuid:pk>/renew/', views.renewBook, name='renew'),
    path('book/<str:pk>/edit/', views.BookUpdateView.as_view(), name='update'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static      # Use static() to add url mapping to serve static files during development (only)
from django.views.generic import RedirectView   # to permanent redirect to new url.

# Add Django site authentication urls (for login, logout, password management)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid  # Required for unique book instances
from datetime import date

# Create your models here.




class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'




class Language(models.Model):
    name = models.CharField(max_length=30, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        return self.name



class Genre(models.Model):
        name = models.CharField(max_length=200, help_text='Enter a book genre here')

        def __str__(self):
                return self.name



class Book(models.Model):
        """Model representing a book (but not a specific copy of a book)."""
        title = models.CharField(max_length=200)

        author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)

        summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
        isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

        # ManyToManyField used because genre can contain many books. Books can cover many genres.
        # Genre class has already been defined so we can specify the object above.
        genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

        language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)

        class Meta:
            permissions = (("can_edit_book", "edit book's data"),)

        def __str__(self):
                return self.title

        def get_absolute_url(self):
                return reverse('catalog:detail', args=[str(self.id)])

        def display_genre(self):
            """Create a string for the Genre. This is required to display genre in Admin."""
            return ', '.join(genre.name for genre in self.genre.all()[:3])

        display_genre.short_description = 'Genre'









class BookInstance(models.Model):
        id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
        book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
        imprint = models.CharField(max_length=200)
        due_back = models.DateField(null=True, blank=True)
        borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

        LOAN_STATUS = (
                ('m', 'Maintenance'),
                ('o', 'On loan'),
                ('a', 'Available'),
                ('r', 'Reserved'),
        )

        status = models.CharField(
                max_length=1,
                choices=LOAN_STATUS,
                blank=True,
                default='m',
                help_text='Book availability',
        )

        class Meta:
                ordering = ['due_back']
                permissions = (("can_mark_returned", "Set book as returned"),)

        def __str__(self):
                return f'{self.id} ({self.book.title})'

        @property
        def is_overdue(self):
            if self.due_back and date.today() > self.due_back:
                return True
            return False

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text='Enter a date between now and 4 weeks (default 3).')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # check if date is not past
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # check if data is in allowed range ( +4 weeks from today)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead.'))

        # returning cleaned data is necessary
        return data

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

from .models import Book, BookInstance
from .forms import RenewBookForm
import datetime


# Create your views here.


'''     basic generic class view

class SomeView(generic.DetailView):
    model = Book
    context_object_name = 'books'   # context variable name
    template_name = 'catalog/details.html'  # custom template name  (default: 'model_detail.html')
    queryset = Book.objects.filter(author='abc')    # customise content variable

    # another way to modify data before sending.  (can do the same with queryset variable as above)
    def get_queryset(self):
        return Book.objects

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context
'''




class IndexView(LoginRequiredMixin, generic.ListView,):
    login_url = 'login'
    model = Book
    template_name = 'catalog/index.html'
    context_object_name = 'books'

    def get_queryset(self):
        return Book.objects.all()[:3]


class BookListView(LoginRequiredMixin, generic.ListView):
    login_url = 'login'
    model = Book
    template_name = 'catalog/books.html'
    context_object_name = 'books'


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    login_url = 'login'
    model = Book
    template_name = 'catalog/detail_book.html'


class LoanedBookByUser(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renewBook(request, pk):
    book = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book.due_back = form.cleaned_data['renewal_date']
            book.save()

            return redirect('catalog:borrowed')

    else:
        # default renewal date
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book,
    }

    return render(request, 'catalog/book_renew.html', context)


class BookUpdateView(UpdateView, LoginRequiredMixin, PermissionRequiredMixin):
    model = Book
    login_url = 'login'
    permission_required = ('can_edit_book',)
    fields = '__all__'

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
    {% block title %}
      Library
    {% endblock %}
  </title>

  <!-- Bootstrap core CSS -->
  {% load static %}
  <link href="{% static 'catalog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'catalog/css/heroic-features.css' %}" rel="stylesheet">
  {% block staticFiles %}
  {% endblock %}

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="">Book Library</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <p class="nav-link text-white">welcome, {{ user.username }}</p>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'catalog:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'catalog:books' %}">books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'catalog:borrowed' %}">my book</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">log in</a>
          </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container long-height">
  {% block content %}



  {% endblock %}
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Book Library 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src='{% static "catalog/vendor/jquery/jquery.min.js" %}'></script>
  <script src="{% static 'catalog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

catalog/templates/catalog/book_form.html
{% extends "catalog/base.html" %}

{% block content %}
    <div class="card mt-5 p-3">
      <h1>Update book's date</h1>
      <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
      </form>
    </div>
{% endblock %}

catalog/templates/catalog/book_renew.html
{% extends "catalog/base.html" %}

{% block content %}
    <div class="card mt-5 p-3">
      <h1>Renew: {{ book_instance.book.title }}</h1>
      <p>Borrower: {{ book_instance.borrower }}</p>
      <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

      <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
      </form>
    </div>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "catalog/base.html" %}

{% block content %}

    <h1 class="my-4">Borrowed Books</h1>

    {% if bookinstance_list %}
      {% for bookinst in bookinstance_list %}

      <div class="row p-2 {% if bookinst.is_overdue %}text-danger{% endif %}">
        <div class="col-13">
          <h3>{{ bookinst.book.title }}</h3>
          <p>({{ bookinst.due_back }})</p>
          <div class="d-flex">
            <a class="btn btn-primary mr-5" href="{% url 'catalog:detail' bookinst.book.pk %}">book detail</a>
              {% if perms.catalog.can_mark_returned %}
            <a class="btn btn-primary" href="{% url 'catalog:renew' bookinst.pk %}">Renew</a>
              {% endif %}
          </div>
        </div>
      </div>
      <hr>

      {% endfor %}

    {% else %}

      <div class="row">
        <div class="col-13">
          <h3>There are no books borrowed</h3>
        </div>
      </div>
      <hr>

    {% endif %}

{% endblock %}

catalog/templates/catalog/books.html
{% extends 'catalog/base.html' %}

{% block title %}
    Books
{% endblock %}


{% block content %}

    <!-- Page Heading -->
      <h1 class="my-4">All books
        <small>at one place.</small>
      </h1>


      <!-- list -->
    <div class="row">
    {% for book in books %}

        <div class="col-lg-4 col-sm-6 mb-4">
          <div class="card h-100">
              <div class="card-body">
                  <div class="card-body">
                    <h2 class="card-title">{{ book.title }}</h2>
                    <p class="card-text">{{ book.summary }}</p>
                    <b><p class="card-text">{{ book.author }}</p></b>
                  </div>
              </div>
              <div class="card-footer">
                  <a href="{{ book.get_absolute_url }}" class="btn btn-primary btn-sm">details</a>
              </div>
          </div>
        </div>

    {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/detail_book.html
{% extends 'catalog/base.html' %}

{% block title %}
    {{ book.name }}
{% endblock %}

{% block content %}

<!--    book data-->
    <div class="col-13 mt-4 mb-4">
        <h1>{{ book.title }}</h1>
        <table class="table">
        <tr>
            <th scope="col">Author</th>
            <td>{{ book.author }}</td>
        </tr>
        <tr>
            <th scope="col">Summary</th>
            <td>{{ book.summary }}</td>
        </tr>
        <tr>
            <th scope="col">ISBN</th>
            <td>{{ book.isbn }}</td>
        </tr>
        <tr>
            <th scope="col">Language</th>
            <td>{{ book.language }}</td>
        </tr>
        <tr>
            <th scope="col">Genre</th>
            <td>{{ book.genre.all|join:',' }}</td>
        </tr>
        {% if perms.catalog.can_edit_book %}
            <tr>
                <a class="btn btn-primary" href="{% url 'catalog:update' book.pk %}">edit</a>
            </tr>
        {% endif %}
        </table>
    </div>

    {% if book.bookinstance_set.count > 0 %}

<!--    book instance-->
    <table class="table">
      <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Imprint</th>
            <th scope="col">status</th>
            <th scope="col">Due back</th>
        </tr>
      </thead>
      <tbody>
      {% for bookObj in book.bookinstance_set.all %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ bookObj.imprint }}</td>

          {% if bookObj.status == 'm' %}
            <td>Maintenance</td>
          {% elif bookObj.status == 'o' %}
            <td>On loan</td>
          {% elif bookObj.status == 'a' %}
            <td>Available</td>
          {% elif bookObj.status == 'r' %}
            <td>Reserved</td>
          {% endif %}

          <td>{{ bookObj.due_back }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    {% else %}

    <h1 class="ml-auto mr-auto mt-4 mb-4 text-warning">Books aren't available yet</h1>

    {% endif %}

{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}



{% block content %}

    <!-- Heading Row -->
    <div class="row align-items-center my-5">
      <div class="col-lg-7">
        {% load static %}
        <img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'catalog/img/library.jpg' %}" alt="">
      </div>
      <!-- /.col-lg-8 -->
      <div class="col-lg-5">
        <h1 class="font-weight-light">Opening The Door To Knowledge.</h1>
        <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
        <a class="btn btn-primary" href="{% url 'catalog:books' %}">Explore</a>
      </div>
      <!-- /.col-md-4 -->
    </div>
    <!-- /.row -->

    <!-- Call to Action Well -->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
      <div class="card-body">
        <p class="text-white m-0">Books Can Be Dangerous, The Best Ones Should Be Labeled, “This Could Change Your Life.”</p>
      </div>
    </div>

    <!-- Content Row -->
    <div class="row">

    {% for book in books %}
        <div class="col-md-4 mb-5">
            <div class="card h-100">
              <div class="card-body">
                <h2 class="card-title">{{ book.title }}</h2>
                <p class="card-text">{{ book.summary }}</p>
              </div>
              <div class="card-footer">
                <a href="{{ book.get_absolute_url }}" class="btn btn-primary btn-sm">details</a>
              </div>
            </div>
        </div>
    {% endfor %}

    </div>

    <!-- /.row -->

{% endblock %}